[package]
name = "web_storage_indexeddb"
version = "0.1.0"
edition = "2024"

[dependencies]
persistence = { path = "../persistence" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
idb = "0.6.4"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
web-time = "1"
